In [1]:
import pandas as pd

In [3]:
time_res = pd.read_csv("time.log", sep=";", skiprows=10)
acc_res = pd.read_csv("accuracy.log", sep=";", skiprows=10)

merged_results = time_res.merge(acc_res, how='left', on=['Rounds', 'Epochs'])

In [4]:
merged_results

    Rounds  Epochs         Time   Accuracy
0        1      10    50.567925  36.277174
1        5      10    63.653559  56.657609
2        9      10   117.653279  75.543478
3       13      10   178.370419  79.483696
4       17      10   228.739985  82.336957
5       21      10   275.638741  83.967391
6       25      10   329.787085  86.141304
7        1      20    32.645840  36.820652
8        5      20   139.214672  76.766304
9        9      20   248.814863  84.103261
10      13      20   366.609064  84.918478
11      17      20   454.300097  88.451087
12      21      20   533.106685  89.945652
13      25      20   666.144935  89.673913
14       1      30    44.290992  53.125000
15       5      30   200.731747  81.385870
16       9      30   349.524468  85.461957
17      13      30   523.170835  88.722826
18      17      30   682.144842  90.353261
19      21      30   842.693516  91.983696
20      25      30  1000.132610  92.663043
21       1      40    54.145266  57.336957
22       5      40   271.214903  83.831522
23       9      40   486.157912  88.179348

In [9]:
import matplotlib.pyplot as plt

rounds_9 = merged_results[merged_results['Rounds'] == 9]

rounds_9

    Rounds  Epochs        Time   Accuracy
2        9      10  117.653279  75.543478
9        9      20  248.814863  84.103261
16       9      30  349.524468  85.461957
23       9      40  486.157912  88.179348